### ISSUE TITLE
Integration with Magento 2.2.6

### ISSUE THREAD

**Issue by Cristiano81** [ekomi-ltd/eKomi-integration-magento-2#7]
After update Magento to 2.2.6 and Ekomi Integration to 1.3.0,
we have this error on error_log while placing order:

[20-Sep-2018 13:22:44 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Ekomi\EkomiIntegration\Observer\SendOrderToEkomi::__construct() must be an instance of Magento\Framework\HTTP\Client\Curl, instance of Ekomi\EkomiIntegration\Helper\Data given, called in /home/hdivineq/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 111 and defined in /home/hdivineq/public_html/app/code/Ekomi/EkomiIntegration/Observer/SendOrderToEkomi.php:53
Stack trace:
#0 /home/hdivineq/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Ekomi\EkomiIntegration\Observer\SendOrderToEkomi->__construct(Object(Ekomi\EkomiIntegration\Helper\Data), Object(Magento\Framework\Logger\Monolog), Array)
#1 /home/hdivineq/public_html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Ekomi\\EkomiInte...', Array)
#2 /home/hdivineq/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\Object in /home/hdivineq/public_html/app/code/Ekomi/EkomiIntegration/Observer/SendOrderToEkomi.php on line 53

**Comment by Cristiano81** [comment]
issue resolved, 
in previous version of the integration the file inside the observer folder was 
sendOrderToEkomi.php
now the file has been renamed to
SendOrderToEkomi.php

the first uppercase letter cause a duplicate file inside observer that cause the Fatal error,
remove the old file to avoid this issue
